### ISSUE TITLE
The bot should always push the google3 status

### ISSUE THREAD

**Issue by IgorMinar** [angular/github-robot#40]
The bot should always pushes the g3 status to all PR. If a PR does not have g3 impact, it should be marked as green with a status note stating "No google3 impact.".

This change is blocking: https://github.com/angular/angular/pull/28613

**Comment by ocombe** [comment]
it should already be the case, do you have an example where it didn't happen ?

**Comment by IgorMinar** [comment]
oh. I think you are right. I saw it on angular/angular#28613

either I missed it, or it just took a bit.

thanks for confirming.

**Comment by ocombe** [comment]
There was a github outage yesterday, maybe one of the events was missed in a PR.
The G3 status is added on the "synchronize" event which is sent when you push a new commit to a PR (or force push)

**Comment by IgorMinar** [comment]
that's a possibility.
